# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::398692602192:role/test-Role-K9KPNU5WFO8J
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: gitops-argocd

      run: |
        # Build a docker container and push it to ECR
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash"

    - name: Down devops repo
      uses: actions/checkout@v2
      with:
        repository: tranvanloc412/argo-devops
        path: devops
        token: ${{ secrets.PUSH_TOKEN }}

    - name: check repos
      run: |
        ls
        ls devops

    - name: Update Version
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          version=$(cat ./devops/values.yaml | grep version: | awk '{print $2}')
          sed -i "s/$version/${GITHUB_REF##*/}-$git_hash/" ./devops/values.yaml
          cat ./devops/values.yaml
          
    # - name: Commit and push changes
    #   uses: devops-infra/action-commit-push@v0.3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     commit_message: Version updated
    - name: Commit and push changes
      env:
        REPO_KEY: ${{ secrets.PUSH_TOKEN }}
        USERNAME: github-actions[bot]
      run: |
        cd devops
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Update image"
        git push https://$USERNAME:$REPO_KEY@github.com/tranvanloc412/argo-devops.git # This works
        ls
        # cd argo-devops
        
    - name: tfsec
      uses: tfsec/tfsec-pr-commenter-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    #  cd documentation
        # git config --local user.name "github-actions[bot]"
        # git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # git add -A
        # git commit -m "Update image"
        # git push https://$USERNAME:$REPO_KEY@github.com/myorg/documentation.git